config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :home, only: [:index]
  resources :students, only: [:new, :create]
  resources :courses, only: [:index, :new, :create]
  resources :results, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/course.rb
class Course < ApplicationRecord
  ### Associations
  has_many :results
  has_many :students, through: :results

  ### Validations
  validates :name, presence: true, uniqueness: true
end

app/models/result.rb
class Result < ApplicationRecord
  ### Associations
  belongs_to :student
  belongs_to :course

  ### Validations
  validates :student, :course, :grade, presence: true
  validates :grade, inclusion: { in: %w[A B C D E F] }
end

app/models/student.rb
class Student < ApplicationRecord
  ### Associations
  has_many :results
  has_many :courses, through: :results

  ### Validations
  validates :first_name, :family_name, :date_of_birth, presence: true
  validates :first_name, :family_name, length: { maximum: 25 }

  validate :validate_age

  ### Instance Method
  def full_name
    "#{self.first_name} #{self.family_name}"
  end

  private

  def validate_age
    if date_of_birth.present? && date_of_birth > 10.years.ago.to_date
      return errors.add(:date_of_birth, "is invalid, must be over 10 years of age")
    end

    if date_of_birth.present? && date_of_birth < 100.years.ago.to_date
      return errors.add(:date_of_birth, "is invalid, must be under 100 years of age")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end

  def new
    @courses = Course.all
    @course = Course.new
  end

  def create
    @course = Course.new(create_params)
    saved = @course.save

    @courses = Course.all

    if saved
      render turbo_stream:
               turbo_stream.replace(
                 'courses_table',
                 partial: 'courses/courses_table',
                 locals: { courses: @courses }
               )
    else
      respond_to do |format|
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def create_params
    params.require(:course).permit(:name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @students = Student.all
    @courses = Course.all
    @results = Result.all
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :fetch_results, only: [:new, :create]

  def new
    @result = Result.new
  end

  def create
    @result = update_result_if_exists(create_params) || Result.create(create_params)

    if @result.errors.any?
      respond_to do |format|
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @results.errors, status: :unprocessable_entity }
      end
    else
      render turbo_stream:
               turbo_stream.replace(
                 'results_table',
                 partial: 'results/results_table',
                 locals:  { results: @results }
               )
    end
  end

  private

  def create_params
    params.require(:result).permit(:course_id, :student_id, :grade)
  end

  # Would not implement in controller for future applications
  def update_result_if_exists(params)
    prev_result = Result.find_by(student_id: params[:student_id], course_id: params[:course_id])

    if prev_result.present?
      prev_result.update(params)
      prev_result
    end
  end

  def fetch_results
    @results = Result.all
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :fetch_students, only: [:new, :create]
  def new
    @student = Student.new
  end

  def create
    @student = Student.new(create_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to new_student_url, notice: "Student was successfully added." }
        format.json { render new, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def create_params
    params.require(:student).permit(:first_name, :family_name, :date_of_birth)
  end

  def fetch_students
    @students = Student.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/courses/_courses_table.html.erb
<%= turbo_frame_tag 'courses_table' do %>
  <table class="table">
    <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Course Name</th>
      <th scope="col">Date Created</th>
    </tr>
    </thead>
    <tbody>
    <% courses&.each do |course| %>
      <tr>
        <th scope="row"><%= course.id %></th>
        <td><%= course.name %></td>
        <td><%= course.created_at.strftime("%m-%d-%Y") %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

app/views/courses/new.html.erb
<% if @course.errors.any? %>
  <% @course.errors.full_messages.each do |message| %>
    <div class="alert alert-danger alert-dismissible fade show mb-0" role="alert">
      <%= message %>.
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
<% end %>

<div class="new-courses-container">
  <%= render partial: 'courses/courses_table', locals: { courses: @courses } %>

  <div class="add-courses-container">
    <%= form_for(@course, url: courses_url) do |f| %>
      <div class="course-form mb-3">
        <%= f.label 'Course Name', class: 'me-2' %>
        <%= f.text_field :name %>
      </div>

      <%= f.submit 'Add Course', class: 'btn btn-secondary' %>
    <% end %>
  </div>
</div>

app/views/grades/new.html.erb
<% if @grade.errors.any? %>
  <% @grade.errors.full_messages.each do |message| %>
    <div class="alert alert-danger alert-dismissible fade show mb-0" role="alert">
      <%= message %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end  %>
<% end %>

<div class="grade-new-page">
  <div class="grade-submission">
    <%= form_for(@grade, url: grades_url) do |f| %>
      <div class="mb-3">
        <%= f.label 'Student' %>
        <%= f.collection_select(:student_id, Student.all, :id, :full_name, prompt: true) %>
      </div>
      <div class="mb-3">
        <%= f.label 'Course' %>
        <%= f.collection_select(:course_id, Course.all, :id, :name, prompt: true) %>
      </div>
      <div class="mb-3">
        <%= f.label 'Grade' %>
        <%= f.select :grade, %w[A B C D E F] %>
      </div>

      <%= f.submit 'Submit Grade', class: 'btn btn-secondary' %>
  <% end %>
  </div>

  <%= render partial: 'grades_table', locals: { grades: @grades } %>

</div>

app/views/home/index.html.erb
<div class="home-index-container">

  <div class="index mx-3 mb-4">
    <h4 class="text-info">Students</h4>
    <%= render partial: 'students/students_table', locals: { students: @students } %>
    <div class="mb-3">
      <!--      <h6 class="mb-2">Create new students here:</h6>-->
      <%= link_to 'Create Student', new_student_url, class: 'btn btn-secondary' %>
    </div>
  </div>

  <div class="index mx-3 mb-4">
    <h4 class="text-info">Courses</h4>
    <%= render partial: 'courses/courses_table', locals: { courses: @courses } %>
    <div class="mb-3">
      <!--      <h6 class="mb-2">Create new courses here:</h6>-->
      <%= link_to 'Create Courses', new_course_url, class: 'btn btn-secondary' %>
    </div>
  </div>

  <div class="index mx-3 mb-4">
    <h4 class="text-info">Results</h4>
    <%= render partial: 'results/results_table', locals: { results: @results || [] } %>
    <div class="mb-3">
      <!--      <h6 class="mb-2">Assign new grades here:</h6>-->
      <%= link_to 'Assign Grades', new_result_url, class: 'btn btn-secondary' %>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg text-secondary navbar-shyftlabs">
  <div class="container-fluid">
    <div>
      <%= link_to 'Students', new_student_url, class: 'text-decoration-none text-light' %>
      <%= link_to 'Courses', new_course_url, class: 'text-decoration-none text-light' %>
      <%= link_to 'Results', new_result_url, class: 'text-decoration-none text-light' %>
    </div>
    <a class="navbar-brand ms-2 text-light" href="/">Shyftlabs 💠</a>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShyftlabsAssignment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <% if flash[:notice] %>
    <div class="alert alert-success alert-dismissible fade show mb-0" role="alert">
      <%= flash[:notice] %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
  <% if flash[:alert] %>
    <div class="alert alert-warning alert-dismissible fade show mb-0" role="alert">
      <%= flash[:alert] %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/results/_results_table.html.erb
<%= turbo_frame_tag 'results_table' do %>
  <table class="table">
    <thead>
    <tr>
      <th scope="col">Course</th>
      <th scope="col">Student</th>
      <th scope="col">Grade</th>
    </tr>
    </thead>
    <tbody>
    <% results.each do |result| %>
      <tr>
        <th scope="row"><%= result.course.name %></th>
        <td><%= result.student.full_name %></td>
        <td><%= result.grade %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

app/views/results/index.html.erb
<div class="grade-index-page">
grades
</div>

app/views/results/new.html.erb
<% if @result.errors.any? %>
  <% @result.errors.full_messages.each do |message| %>
    <div class="alert alert-danger alert-dismissible fade show mb-0" role="alert">
      <%= message %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
<% end %>

<div class="results-new-page">
  <div class="result-submission me-4">
    <%= form_for(@result, url: results_url) do |f| %>
      <div class="mb-3">
        <%= f.label 'Student' %>
        <%= f.collection_select(:student_id, Student.all, :id, :full_name, prompt: true) %>
      </div>
      <div class="mb-3">
        <%= f.label 'Course' %>
        <%= f.collection_select(:course_id, Course.all, :id, :name, prompt: true) %>
      </div>
      <div class="mb-3">
        <%= f.label 'Grade' %>
        <%= f.select :grade, %w[A B C D E F] %>
      </div>

      <%= f.submit 'Submit Grade', class: 'btn btn-secondary' %>
  <% end %>
  </div>

  <%= render partial: 'results_table', locals: { results: @results } %>
</div>

app/views/students/_students_table.html.erb
<%= turbo_frame_tag 'students_table' do %>
  <table class="table">
    <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">First Name</th>
      <th scope="col">Family Name</th>
      <th scope="col">Date of Birth</th>
    </tr>
    </thead>
    <tbody>
    <% students.each do |student| %>
      <tr>
        <th scope="row"><%= student.id %></th>
        <td><%= student.first_name %></td>
        <td><%= student.family_name %></td>
        <td><%= student.date_of_birth.to_s %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

app/views/students/index.html.erb
<div class="students-index-container">
  <div class="index mb-3">
    <table class="table">
      <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">First Name</th>
        <th scope="col">Family Name</th>
        <th scope="col">Date of Birth</th>
      </tr>
      </thead>
      <tbody>
      <% @students.each do |student| %>
        <tr>
          <th scope="row"><%= student.id %></th>
          <td><%= student.first_name %></td>
          <td><%= student.family_name %></td>
          <td><%= student.date_of_birth.to_s %></td>
        </tr>
      <% end %>
      </tbody>
    </table>

  </div>
  <div class="create-student-container">
    <h6 class="mb-3">Create new students here:</h6>

    <%= link_to 'Create Student', new_student_url, class: 'btn btn-secondary' %>


  </div>
</div>

app/views/students/new.html.erb
<% if @student.errors.any? %>
    <% @student.errors.full_messages.each do |message| %>
    <div class="alert alert-danger mb-0" role="alert">
      <%= message %>.
    </div>
    <% end  %>
<% end %>

<div class="new-student-container">
  <h6 class="mb-3">Create a new student:</h6>

  <%= form_for(@student, url: students_path) do |f| %>
    <div class="field">
      <%= f.label 'First Name' %>
      <%= f.text_field :first_name, maxLength: 25 %>
    </div>

    <div class="field">
      <%= f.label 'Family Name' %>
      <%= f.text_field :family_name, maxLength: 25 %>
    </div>

    <div class="field">
      <%= f.label 'Date of Birth' %>
      <%= f.date_field :date_of_birth %>
    </div>

    <%= f.submit 'Add Student', class: 'btn btn-secondary' %>
  <% end %>
</div>